# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.rename_column("api_keys", "superuser", "full_access")

    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.rename_column("api_keys", "full_access", "superuser")
    """
    Write your rollback migrations here.
    """
