# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns(
        "servers",
        cf_project_id=peewee.IntegerField(default=0),
        cf_file_id=peewee.IntegerField(default=0),
        cf_purge_paths=peewee.TextField(default="mods\nconfig\ndefaultconfigs\nkubejs"),
        cf_overlay_dir=peewee.CharField(default=""),
    )
    migrator.add_columns(
        "crafty_settings",
        curseforge_api_key=peewee.CharField(default=""),
    )


def rollback(migrator, database, **kwargs):
    migrator.drop_columns(
        "servers",
        ["cf_project_id", "cf_file_id", "cf_purge_paths", "cf_overlay_dir"],
    )
    migrator.drop_columns("crafty_settings", ["curseforge_api_key"])
