# Generated by database migrator
import peewee


LEGACY_MASK_LENGTH = 8
TARGET_MASK_LENGTH = 10
FILES_PERMISSION_INDEX = 5


def _sanitize_mask(raw_mask):
    raw_text = "" if raw_mask is None else str(raw_mask)
    return "".join("1" if bit == "1" else "0" for bit in raw_text)


def _expand_server_permissions_mask(raw_mask):
    sanitized = _sanitize_mask(raw_mask)
    if len(sanitized) >= TARGET_MASK_LENGTH:
        return sanitized[:TARGET_MASK_LENGTH]

    if len(sanitized) < LEGACY_MASK_LENGTH:
        sanitized = sanitized.ljust(LEGACY_MASK_LENGTH, "0")

    if len(sanitized) == LEGACY_MASK_LENGTH:
        files_bit = sanitized[FILES_PERMISSION_INDEX]
        return sanitized + files_bit + files_bit

    if len(sanitized) == LEGACY_MASK_LENGTH + 1:
        return sanitized + sanitized[-1]

    return sanitized.ljust(TARGET_MASK_LENGTH, "0")[:TARGET_MASK_LENGTH]


def _shrink_server_permissions_mask(raw_mask):
    sanitized = _sanitize_mask(raw_mask)
    if len(sanitized) < LEGACY_MASK_LENGTH:
        return sanitized.ljust(LEGACY_MASK_LENGTH, "0")
    return sanitized[:LEGACY_MASK_LENGTH]


def migrate(migrator, database, **kwargs):
    db = database

    class RoleServers(peewee.Model):
        role_id = peewee.IntegerField()
        server_id = peewee.CharField()
        permissions = peewee.CharField(default="0000000000")

        class Meta:
            table_name = "role_servers"
            database = db
            primary_key = peewee.CompositeKey("role_id", "server_id")

    class ApiKeys(peewee.Model):
        token_id = peewee.AutoField()
        server_permissions = peewee.CharField(default="0000000000")

        class Meta:
            table_name = "api_keys"
            database = db

    for row in RoleServers.select():
        new_mask = _expand_server_permissions_mask(row.permissions)
        if row.permissions != new_mask:
            row.permissions = new_mask
            row.save()

    for row in ApiKeys.select():
        new_mask = _expand_server_permissions_mask(row.server_permissions)
        if row.server_permissions != new_mask:
            row.server_permissions = new_mask
            row.save()
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    db = database

    class RoleServers(peewee.Model):
        role_id = peewee.IntegerField()
        server_id = peewee.CharField()
        permissions = peewee.CharField(default="00000000")

        class Meta:
            table_name = "role_servers"
            database = db
            primary_key = peewee.CompositeKey("role_id", "server_id")

    class ApiKeys(peewee.Model):
        token_id = peewee.AutoField()
        server_permissions = peewee.CharField(default="00000000")

        class Meta:
            table_name = "api_keys"
            database = db

    for row in RoleServers.select():
        old_mask = _shrink_server_permissions_mask(row.permissions)
        if row.permissions != old_mask:
            row.permissions = old_mask
            row.save()

    for row in ApiKeys.select():
        old_mask = _shrink_server_permissions_mask(row.server_permissions)
        if row.server_permissions != old_mask:
            row.server_permissions = old_mask
            row.save()
    """
    Write your rollback migrations here.
    """
