# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("servers", memory_limit_mib=peewee.IntegerField(default=0))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("servers", ["memory_limit_mib"])
    """
    Write your rollback migrations here.
    """

