# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("servers", cpu_affinity=peewee.CharField(default=""))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("servers", ["cpu_affinity"])
    """
    Write your rollback migrations here.
    """
