# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("servers", telemetry_port=peewee.IntegerField(default=0))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("servers", ["telemetry_port"])
    """
    Write your rollback migrations here.
    """
