# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("users", datetime_format=peewee.CharField(default="auto"))


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("users", ["datetime_format"])
