# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns(
        "users",
        dashboard_columns=peewee.CharField(
            default="server,actions,cpuUsage,memUsage,size,players,status"
        ),
    )


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("users", ["dashboard_columns"])
