# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("server_stats", telemetry_tps=peewee.FloatField(null=True, default=None))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("server_stats", ["telemetry_tps"])
    """
    Write your rollback migrations here.
    """
