# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("server_stats", mem_capacity_raw=peewee.IntegerField(default=0))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("server_stats", ["mem_capacity_raw"])
    """
    Write your rollback migrations here.
    """

